dbSchema: yazabara

logging:
  level:
    org.hibernate: 'ERROR'

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
    parameters:
      dbSchema: ${dbSchema}
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    properties:
      hibernate.default_schema: ${dbSchema}
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:yazdb;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS ${dbSchema};