dbSchema: yazabara

app:
  use-test-data: true

logging:
  level:
    org.hibernate: 'ERROR'
    com.yazabara: 'INFO'

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
    parameters:
      dbSchema: ${dbSchema}
  thymeleaf:
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    properties:
      hibernate.default_schema: ${dbSchema}
      hibernate.enable_lazy_load_no_trans: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:yazdb;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS ${dbSchema};