# application custom configuration
app:
  version: 1.0.0
  dbSchema: yazabara

# logging configuration
logging:
  level:
    org.hibernate: 'ERROR'
    com.yazabara: 'INFO'

# application port
server:
  port: 8089

# oauth2 spring security configuration
security:
  oauth2:
    client:
      clientId: 57cb6dca97af2b1e9ace
      clientSecret: ffc9951ccd977280b7b07f296dc99504a078e7d4
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
      preferTokenInfo: false

# spring configuration
spring:
  mvc:
    view:
      suffix: .html
      prefix: classpath:templates/
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
    parameters:
      dbSchema: ${app.dbSchema}
  thymeleaf:
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    properties:
      hibernate.default_schema: ${app.dbSchema}
      hibernate.enable_lazy_load_no_trans: true
    show-sql: true
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:yazdb;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS ${app.dbSchema};